package pe.com.glovo.entidades;
// Generated 28-jun-2019 12:16:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Dealer generated by hbm2java
 */
@Entity
@Table(name = "dealer", catalog = "glovo")
public class Dealer implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idDealer;
	private Pedido pedido;
	private String nombre;
	private String estado;
	private String direccionAenviar;

	public Dealer() {
	}

	public Dealer(int idDealer) {
		this.idDealer = idDealer;
	}

	public Dealer(int idDealer, Pedido pedido, String nombre, String estado, String direccionAenviar) {
		this.idDealer = idDealer;
		this.pedido = pedido;
		this.nombre = nombre;
		this.estado = estado;
		this.direccionAenviar = direccionAenviar;
	}

	@Id

	@Column(name = "idDealer", unique = true, nullable = false)
	public int getIdDealer() {
		return this.idDealer;
	}

	public void setIdDealer(int idDealer) {
		this.idDealer = idDealer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@Column(name = "nombre", length = 45)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "estado", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@Column(name = "direccionAEnviar", length = 100)
	public String getDireccionAenviar() {
		return this.direccionAenviar;
	}

	public void setDireccionAenviar(String direccionAenviar) {
		this.direccionAenviar = direccionAenviar;
	}

}
