package pe.com.glovo.entidades;
// Generated 28-jun-2019 12:16:57 by Hibernate Tools 4.3.1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Detallepedido generated by hbm2java
 */
@Entity
@Table(name = "detallepedido", catalog = "glovo")
public class Detallepedido implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idDetallePedido;
	private Pedido pedido;
	private Persona persona;
	private Producto producto;
	private Integer cantidad;
	private Long subtotal;
	private Long igv;
	private Long total;

	public Detallepedido() {
	}

	public Detallepedido(int idDetallePedido) {
		this.idDetallePedido = idDetallePedido;
	}

	public Detallepedido(int idDetallePedido, Pedido pedido, Persona persona, Producto producto, Integer cantidad,
			Long subtotal, Long igv, Long total) {
		this.idDetallePedido = idDetallePedido;
		this.pedido = pedido;
		this.persona = persona;
		this.producto = producto;
		this.cantidad = cantidad;
		this.subtotal = subtotal;
		this.igv = igv;
		this.total = total;
	}

	@Id

	@Column(name = "idDetallePedido", unique = true, nullable = false)
	public int getIdDetallePedido() {
		return this.idDetallePedido;
	}

	public void setIdDetallePedido(int idDetallePedido) {
		this.idDetallePedido = idDetallePedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPedido")
	public Pedido getPedido() {
		return this.pedido;
	}

	public void setPedido(Pedido pedido) {
		this.pedido = pedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPersona")
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idProducto")
	public Producto getProducto() {
		return this.producto;
	}

	public void setProducto(Producto producto) {
		this.producto = producto;
	}

	@Column(name = "cantidad")
	public Integer getCantidad() {
		return this.cantidad;
	}

	public void setCantidad(Integer cantidad) {
		this.cantidad = cantidad;
	}

	@Column(name = "subtotal", precision = 10, scale = 0)
	public Long getSubtotal() {
		return this.subtotal;
	}

	public void setSubtotal(Long subtotal) {
		this.subtotal = subtotal;
	}

	@Column(name = "igv", precision = 10, scale = 0)
	public Long getIgv() {
		return this.igv;
	}

	public void setIgv(Long igv) {
		this.igv = igv;
	}

	@Column(name = "total", precision = 10, scale = 0)
	public Long getTotal() {
		return this.total;
	}

	public void setTotal(Long total) {
		this.total = total;
	}

}
