package pe.com.glovo.entidades;
// Generated 28-jun-2019 12:16:57 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pagos generated by hbm2java
 */
@Entity
@Table(name = "pagos", catalog = "glovo")
public class Pagos implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private int idPago;
	private Tipopago tipopago;
	private Date fechaPago;
	private Long montoApagar;
	private String estado;
	private Set<Pedido> pedidos = new HashSet<Pedido>(0);

	public Pagos() {
	}

	public Pagos(int idPago) {
		this.idPago = idPago;
	}

	public Pagos(int idPago, Tipopago tipopago, Date fechaPago, Long montoApagar, String estado, Set<Pedido> pedidos) {
		this.idPago = idPago;
		this.tipopago = tipopago;
		this.fechaPago = fechaPago;
		this.montoApagar = montoApagar;
		this.estado = estado;
		this.pedidos = pedidos;
	}

	@Id

	@Column(name = "idPago", unique = true, nullable = false)
	public int getIdPago() {
		return this.idPago;
	}

	public void setIdPago(int idPago) {
		this.idPago = idPago;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idTipoPago")
	public Tipopago getTipopago() {
		return this.tipopago;
	}

	public void setTipopago(Tipopago tipopago) {
		this.tipopago = tipopago;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaPago", length = 26)
	public Date getFechaPago() {
		return this.fechaPago;
	}

	public void setFechaPago(Date fechaPago) {
		this.fechaPago = fechaPago;
	}

	@Column(name = "montoApagar", precision = 10, scale = 0)
	public Long getMontoApagar() {
		return this.montoApagar;
	}

	public void setMontoApagar(Long montoApagar) {
		this.montoApagar = montoApagar;
	}

	@Column(name = "estado", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pagos")
	public Set<Pedido> getPedidos() {
		return this.pedidos;
	}

	public void setPedidos(Set<Pedido> pedidos) {
		this.pedidos = pedidos;
	}

}
