package pe.com.glovo.entidades;
// Generated 28-jun-2019 12:16:57 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Tipopago generated by hbm2java
 */
@Entity
@Table(name = "tipopago", catalog = "glovo")
public class Tipopago implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idTipoPago;
	private String descripcion;
	private Set<Pagos> pagoses = new HashSet<Pagos>(0);

	public Tipopago() {
	}

	public Tipopago(String descripcion, Set<Pagos> pagoses) {
		this.descripcion = descripcion;
		this.pagoses = pagoses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idTipoPago", unique = true, nullable = false)
	public Integer getIdTipoPago() {
		return this.idTipoPago;
	}

	public void setIdTipoPago(Integer idTipoPago) {
		this.idTipoPago = idTipoPago;
	}

	@Column(name = "descripcion", length = 45)
	public String getDescripcion() {
		return this.descripcion;
	}

	public void setDescripcion(String descripcion) {
		this.descripcion = descripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipopago")
	public Set<Pagos> getPagoses() {
		return this.pagoses;
	}

	public void setPagoses(Set<Pagos> pagoses) {
		this.pagoses = pagoses;
	}

}
