//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.31 at 11:24:54 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema
(namespace = "http://glovo.com.pe/GlovoSOAP/types", 
elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package pe.com.glovo.soap.types;
