package pe.com.glovo.soap.entidades;
// Generated 28-jun-2019 12:16:57 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Pedido generated by hbm2java
 */
@Entity
@Table(name = "pedido", catalog = "glovo")
public class Pedido implements java.io.Serializable {

	private static final long serialVersionUID = 1L;
	private Integer idPedido;
	private Pagos pagos;
	private Date fechaPedido;
	private Date fechaEntrega;
	private String estado;
	private Set<Dealer> dealers = new HashSet<Dealer>(0);
	private Set<Detallepedido> detallepedidos = new HashSet<Detallepedido>(0);

	public Pedido() {
	}

	public Pedido(Pagos pagos, Date fechaPedido, Date fechaEntrega, String estado, Set<Dealer> dealers,
			Set<Detallepedido> detallepedidos) {
		this.pagos = pagos;
		this.fechaPedido = fechaPedido;
		this.fechaEntrega = fechaEntrega;
		this.estado = estado;
		this.dealers = dealers;
		this.detallepedidos = detallepedidos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "idPedido", unique = true, nullable = false)
	public Integer getIdPedido() {
		return this.idPedido;
	}

	public void setIdPedido(Integer idPedido) {
		this.idPedido = idPedido;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "idPago")
	public Pagos getPagos() {
		return this.pagos;
	}

	public void setPagos(Pagos pagos) {
		this.pagos = pagos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaPedido", length = 26)
	public Date getFechaPedido() {
		return this.fechaPedido;
	}

	public void setFechaPedido(Date fechaPedido) {
		this.fechaPedido = fechaPedido;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "fechaEntrega", length = 26)
	public Date getFechaEntrega() {
		return this.fechaEntrega;
	}

	public void setFechaEntrega(Date fechaEntrega) {
		this.fechaEntrega = fechaEntrega;
	}

	@Column(name = "estado", length = 10)
	public String getEstado() {
		return this.estado;
	}

	public void setEstado(String estado) {
		this.estado = estado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<Dealer> getDealers() {
		return this.dealers;
	}

	public void setDealers(Set<Dealer> dealers) {
		this.dealers = dealers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pedido")
	public Set<Detallepedido> getDetallepedidos() {
		return this.detallepedidos;
	}

	public void setDetallepedidos(Set<Detallepedido> detallepedidos) {
		this.detallepedidos = detallepedidos;
	}

}
